//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int CustomerDetailsid { get; set; }
        public string Customername { get; set; }
        public string ShippingAddress { get; set; }
        public string PhoneNo { get; set; }
        public System.DateTime Createdate { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
